version: 2
jobs:
  build-and-test:
    macos:
      xcode: "14.0.1"
    steps:
      - checkout
      - run:
          name: Fastlane Install
          command: brew install fastlane
      - run:
          name: Fastlane tests1
          command: fastlane tests

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
