name: iOS starter workflow

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test iOS app
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Tests1
        run: |
          brew install fastlane
          fastlane tests
      - name: Run Tests2
        run: |
          fastlane tests       
